/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{ts,tsx}'],
  presets: [require('nativewind/preset')],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#006E1C',
          container: '#4CAF50',
          fixed: '#94F990',
          'fixed-dim': '#78DC77',
        },
        secondary: {
          DEFAULT: '#4355B9',
          container: '#8596FF',
          fixed: '#DEE0FF',
          'fixed-dim': '#BAC3FF',
        },
        tertiary: {
          DEFAULT: '#785900',
          container: '#C49400',
          fixed: '#FFDF9E',
          'fixed-dim': '#FABD00',
        },
        error: {
          DEFAULT: '#BA1A1A',
          container: '#FFDAD6',
        },
        surface: {
          DEFAULT: '#F9F9F9',
          dim: '#DADADA',
          bright: '#F9F9F9',
          'container-lowest': '#FFFFFF',
          'container-low': '#F3F3F3',
          container: '#EEEEEE',
          'container-high': '#E8E8E8',
          'container-highest': '#E2E2E2',
          variant: '#E2E2E2',
        },
        'on-surface': {
          DEFAULT: '#1A1C1C',
          variant: '#3F4A3C',
        },
        'on-primary': '#FFFFFF',
        'on-secondary': '#FFFFFF',
        'on-tertiary': '#FFFFFF',
        'on-error': '#FFFFFF',
        outline: {
          DEFAULT: '#6F7A6B',
          variant: '#BECAB9',
        },
        'inverse-surface': '#2F3131',
        'inverse-on-surface': '#F0F1F1',
        'inverse-primary': '#78DC77',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        '2xl': '48px',
        '3xl': '64px',
      },
      borderRadius: {
        DEFAULT: '16px',
        sm: '8px',
        lg: '32px',
        xl: '48px',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Manrope', 'System'],
        body: ['Manrope', 'System'],
        label: ['Plus Jakarta Sans', 'System'],
      },
      fontSize: {
        'display-lg': ['40px', { lineHeight: '48px', fontWeight: '800' }],
        'display-sm': ['34px', { lineHeight: '40px', fontWeight: '800' }],
        'headline-lg': ['28px', { lineHeight: '34px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '30px', fontWeight: '700' }],
        'title-lg': ['20px', { lineHeight: '26px', fontWeight: '700' }],
        'title-md': ['16px', { lineHeight: '22px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'label-sm': ['10px', { lineHeight: '14px', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};
