/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{ts,tsx}'],
  presets: [require('nativewind/preset')],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#E8F5E9',
          100: '#C8E6C9',
          200: '#A5D6A7',
          300: '#81C784',
          400: '#66BB6A',
          DEFAULT: '#4CAF50',
          500: '#4CAF50',
          600: '#43A047',
          700: '#388E3C',
          800: '#2E7D32',
          900: '#1B5E20',
          light: '#81C784',
          dark: '#388E3C',
        },
        accent: {
          DEFAULT: '#FF9800',
          light: '#FFB74D',
          dark: '#F57C00',
        },
        semantic: {
          success: '#4CAF50',
          warning: '#FF9800',
          error: '#F44336',
          info: '#2196F3',
          protein: '#5C6BC0',
          carbs: '#FFA726',
          fat: '#EF5350',
          fiber: '#66BB6A',
        },
        surface: {
          background: '#FAFAFA',
          card: '#FFFFFF',
          elevated: '#FFFFFF',
        },
        'surface-dark': {
          background: '#121212',
          card: '#1E1E1E',
          elevated: '#2C2C2C',
        },
        text: {
          primary: '#212121',
          secondary: '#757575',
          disabled: '#BDBDBD',
          inverse: '#FFFFFF',
        },
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        '2xl': '48px',
      },
      borderRadius: {
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '24px',
        full: '9999px',
      },
      fontSize: {
        'display-lg': ['34px', { lineHeight: '40px', fontWeight: '700' }],
        'display-md': ['28px', { lineHeight: '34px', fontWeight: '700' }],
        'headline-lg': ['24px', { lineHeight: '30px', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '26px', fontWeight: '600' }],
        'title-lg': ['18px', { lineHeight: '24px', fontWeight: '500' }],
        'title-md': ['16px', { lineHeight: '22px', fontWeight: '500' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
